library(dplyr)
library(editrules)
library(readxl)
myDataSet =read_excel('/run/media/thecreator/Personal Data/Github/dduc-sem-6/DM Practical File/Book.xlsx')  
print(myDataSet)
E <- editfile('/run/media/thecreator/Personal Data/Github/dduc-sem-6/DM Practical File/rules.txt')
result <- violatedEdits(E,myDataSet)
print(result)
summary(result)
plot(E)
